### ISSUE TITLE
Developing using pipenv vs pip

### ISSUE THREAD

**Issue by jayvdb** [pycampers/dockapt#2]
How should developers install and use `master`.

README says to use pip, but there is no setup.py

There is a pipenv, but `pipenv install` doesnt create a script called `dockapt`

**Comment by devxpy** [comment]
I'm sorry, I got bogged up in some other project and forgot to update it. 

Please wait for a week or so and I will push with some updates, a setup.py and upload it to pypi as well.

[here](https://github.com/pycampers/zproc) is that project, if it piques your interest..

**Comment by devxpy** [comment]
please see the latest commit, i have added a local development section. 

Feel free to contact me by [email](mailto:devxpy@gmail.com) if you want to discuss something.
